import WidgetKit
import SwiftUI

struct WatchGuide_MovieandTVtrackerWidgetExtensionEntry: TimelineEntry {
    let date: Date
}

struct WatchGuide_MovieandTVtrackerWidgetExtensionProvider: TimelineProvider {
    func placeholder(in context: Context) -> WatchGuide_MovieandTVtrackerWidgetExtensionEntry {
        WatchGuide_MovieandTVtrackerWidgetExtensionEntry(date: Date())
    }

    func getSnapshot(in context: Context, completion: @escaping (WatchGuide_MovieandTVtrackerWidgetExtensionEntry) -> Void) {
        completion(WatchGuide_MovieandTVtrackerWidgetExtensionEntry(date: Date()))
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<WatchGuide_MovieandTVtrackerWidgetExtensionEntry>) -> Void) {
        let entry = WatchGuide_MovieandTVtrackerWidgetExtensionEntry(date: Date())
        let timeline = Timeline(entries: [entry], policy: .after(Date().addingTimeInterval(1800)))
        completion(timeline)
    }
}

struct WatchGuide_MovieandTVtrackerWidgetExtensionEntryView: View {
    var entry: WatchGuide_MovieandTVtrackerWidgetExtensionProvider.Entry

    var body: some View {
        Text(entry.date, style: .time)
            .padding(8)
    }
}

struct WatchGuide_MovieandTVtrackerWidgetExtensionWidget: Widget {
    let kind: String = "com.JasonSmith.WatchGuide-MovieandTVtracker.watchguide-movieandtvtrackerwidgetextension.widget"

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: WatchGuide_MovieandTVtrackerWidgetExtensionProvider()) { entry in
            WatchGuide_MovieandTVtrackerWidgetExtensionEntryView(entry: entry)
        }
        .configurationDisplayName("Widget")
        .description("Widget scaffold generated by Milq.")
    }
}

@main
struct WatchGuide_MovieandTVtrackerWidgetExtensionBundle: WidgetBundle {
    var body: some Widget {
        WatchGuide_MovieandTVtrackerWidgetExtensionWidget()
    }
}